<?php
# This file was automatically generated by the MediaWiki 1.23.6
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

# database settings
$wgDBtype = "postgres";
$wgDBname = "mediawiki";
$wgDBuser = "mediawiki";
$wgDBpassword = "very-secret-password";
$wgDBhost = "localhost";
$wgDBport = "12345";
$wgDBmwschema = "public";

# TODO: is it necessary?
#$wgSecretKey = "";

# site paths
$wgSitename = "wiki-scripts tests";
$wgServer = "http://localhost";
$wgScriptPath = "";
$wgStylePath = "/skins";
$wgUsePathInfo = false;     # TODO: maybe reconfigure nginx and enable this
$wgScriptExtension = ".php";
$wgStylePath = "$wgScriptPath/skins";

# site info
$wgLocaltimezone = "UTC";
$wgLanguageCode = "en";

# no emails
$wgEnableEmail = false;
$wgEmailConfirmToEdit = false;

# no uploads - test fixtures are not ready yet...
$wgEnableUploads = false;

# disable all caches
$wgCacheDirectory = false;
$wgEnableSidebarCache = false;
$wgUseFileCache = false;
$wgFileCacheDirectory = false;

# no object cache, it break the tests because it persists across database resets
$wgMainCacheType    = CACHE_NONE;
# session cache has to be persistent, otherwise it would not be possible to log in
$wgSessionCacheType = CACHE_ACCEL;

# misc
$wgShellLocale = "en_US.utf8";

$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['sysop']['deletelogentry'] = true;
$wgGroupPermissions['sysop']['deleterevision'] = true;

# Interwiki extension
wfLoadExtension( 'Interwiki' );
$wgGroupPermissions['sysop']['interwiki'] = true;

# load default skin
wfLoadSkin( 'Vector' );

$wgJobRunRate = 1;
$wgRunJobsAsync = 1;


# debugging
#$wgShowDBErrorBacktrace = true;
#$wgShowExceptionDetails = true;
