"""make rd_namespace nullable

Revision ID: 0f478e8e3585
Revises: b1ca8054f845
Create Date: 2018-08-18 21:24:31.139762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f478e8e3585'
down_revision = 'b1ca8054f845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('redirect', 'rd_namespace',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('redirect', 'rd_namespace',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
