"""removed old_flags column

Revision ID: 1034996130ac
Revises: 33ef5ceb8902
Create Date: 2018-08-04 15:07:35.466782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1034996130ac'
down_revision = '33ef5ceb8902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text', 'old_flags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text', sa.Column('old_flags', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
