"""initial revision

Revision ID: 11180a291e2c
Revises: 
Create Date: 2017-12-28 12:38:19.668357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11180a291e2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
