"""remove rc_ip

Revision ID: 5824cd5ed16d
Revises: 11180a291e2c
Create Date: 2017-12-28 13:45:08.716463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5824cd5ed16d'
down_revision = '11180a291e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('rc_ip', table_name='recentchanges')
    op.drop_column('recentchanges', 'rc_ip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recentchanges', sa.Column('rc_ip', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('rc_ip', 'recentchanges', ['rc_ip'], unique=False)
    # ### end Alembic commands ###
