"""add namespace.ns_protection

Revision ID: c82c483221d6
Revises: 2d3b166fe612
Create Date: 2020-03-07 08:14:53.643467

"""
from alembic import op
import sqlalchemy as sa

# add our project root into the path so that we can import the "ws" module
import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), "../../../.."))

import ws.db.sql_types



# revision identifiers, used by Alembic.
revision = 'c82c483221d6'
down_revision = '2d3b166fe612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('namespace', sa.Column('ns_protection', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('namespace', 'ns_protection')
    # ### end Alembic commands ###
