"""remove namespace name fkey

Revision ID: e90b3409474d
Revises: 7bdc8c859895
Create Date: 2026-01-24 19:20:40.189855

"""
from alembic import op
import sqlalchemy as sa

# add our project root into the path so that we can import the "ws" module
import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), "../../../.."))

import ws.db.sql_types



# revision identifiers, used by Alembic.
revision = 'e90b3409474d'
down_revision = '7bdc8c859895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('namespace_canonical_nsc_id_nsc_name_fkey'), 'namespace_canonical', type_='foreignkey')
    op.drop_constraint(op.f('namespace_starname_nss_id_nss_name_fkey'), 'namespace_starname', type_='foreignkey')
    op.create_index('nsn_id', 'namespace_name', ['nsn_id'], unique=True)
    op.create_foreign_key("namespace_canonical_nsc_id_fkey1", 'namespace_canonical', 'namespace_name', ['nsc_id'], ['nsn_id'], ondelete='CASCADE')
    op.drop_index(op.f('nsn_id_name'), table_name='namespace_name')
    op.create_foreign_key("namespace_starname_nss_id_fkey1", 'namespace_starname', 'namespace_name', ['nss_id'], ['nsn_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("namespace_starname_nss_id_fkey1", 'namespace_starname', type_='foreignkey')
    op.drop_constraint("namespace_canonical_nsc_id_fkey1", 'namespace_canonical', type_='foreignkey')
    op.drop_index('nsn_id', table_name='namespace_name')
    op.create_index(op.f('nsn_id_name'), 'namespace_name', ['nsn_id', 'nsn_name'], unique=True)
    op.create_foreign_key(op.f('namespace_starname_nss_id_nss_name_fkey'), 'namespace_starname', 'namespace_name', ['nss_id', 'nss_name'], ['nsn_id', 'nsn_name'], ondelete='CASCADE')
    op.create_foreign_key(op.f('namespace_canonical_nsc_id_nsc_name_fkey'), 'namespace_canonical', 'namespace_name', ['nsc_id', 'nsc_name'], ['nsn_id', 'nsn_name'], ondelete='CASCADE')
    # ### end Alembic commands ###
